# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('album_genre', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_genre', models.CharField(max_length=100)),
                ('book_date', models.DateField()),
                ('book_front_page', models.FileField(null=True, upload_to='')),
                ('tag', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.author')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('tag', models.CharField(max_length=1000)),
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('phone_no', models.IntegerField(default='0')),
                ('suggestions', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_director', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('romance', 'romance'), ('drama', 'drama'), ('comedy', 'comedy'), ('fiction', 'fiction')], max_length=100)),
                ('tag', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs_name', models.CharField(max_length=100)),
                ('songs_singer', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('rock', 'rock'), ('pop', 'pop'), ('classical', 'classical'), ('hardcore', 'hardcore')], max_length=100)),
                ('songs_file', models.FileField(upload_to='')),
                ('tag', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=100)),
                ('news_link', models.CharField(max_length=1000)),
                ('tag', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1000)),
            ],
        ),
    ]
