# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message_text', models.CharField(max_length=1000)),
                ('message_date', models.DateField()),
                ('tag', models.CharField(max_length=1000)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.CustomUser')),
            ],
        ),
    ]
