# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tag',
        ),
    ]
