# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_remove_message_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.DateTimeField(),
        ),
    ]
