# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20171028_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.FileField(default='static/icon.png', upload_to=''),
        ),
    ]
