# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20171031_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='content',
            field=models.CharField(default='album', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='content',
            field=models.CharField(default='author', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.CharField(default='book', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='messaages', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='content',
            field=models.CharField(default='movie', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='content',
            field=models.CharField(default='music', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.CharField(default='news', max_length=100),
        ),
    ]
