# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20171031_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(default='None', upload_to=''),
        ),
    ]
