# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_auto_20171101_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Love Story', 'Love Story'), ('Suspense', 'Suspense')], max_length=100),
        ),
    ]
